Improve & fix the error message
```
  AssertionError: In struct `Main.var"##all fields failures#565".S`, the field `x` does not have a fully specified type:
    - `x::Vector`

  The complete type is `Array{T, 1} where T`. The current definition specifies 0 type arguments, but the type `Array{T, 1} where T` expects 1 type parameter(s). This means the struct's field currently has an abstract type (it is type unstable), and any access to it will cause a dynamic dispatch.

  If this was a mistake, possibly caused by a change to the `Array` type that introduced new parameters to it, please make sure that your field `x` is fully concrete, with all parameters specified.

  If, instead, this type instability is on purpose, please fully specify the omitted type parameters to silence this message. You can write that as `Array{T, 1} where T`, or possibly in a shorter alias form which this message cannot detect. (E.g. you can write `Vector{T} where T` instead of `Array{T, 1} where T`.)
```